# ================================
# APPLICATION
# ================================
spring.application.name=kanban-backend
server.port=8088


# ================================
# DATABASE - MySQL
# ================================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://mysql-db:3306/kanban_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ================================
# JPA / HIBERNATE
# ================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ================================
# CORS - Pour Angular (localhost:4200)
# ================================
app.cors.allowed-origins=http://intelligent-rh:32000

# ================================
# CLOUD CONFIG
# ================================
spring.cloud.config.enabled=false

# ================================
# EUREKA CLIENT
# ================================
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://discovery:8761/eureka/}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# ================================
# FEIGN CLIENT
# ================================
feign.client.config.default.connectTimeout=5000
feign.client.config.default.readTimeout=5000
feign.client.config.default.loggerLevel=full

# ================================
# JACKSON (FORMAT JSON)
# ================================
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.serialization.indent_output=true
spring.jackson.date-format=yyyy-MM-dd

# ================================
# LOGGING
# ================================
logging.level.org.springframework=INFO
logging.level.tn.esprit.scoutisme=DEBUG

# ================================
# EXTERNAL SERVICES
# ================================
app.services.url=${TALENT_SERVICE_URL:http://talent-management-service:9002}

# ================================
# SPRING (OPTIONNEL)
# ================================
spring.main.allow-bean-definition-overriding=true
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoints.web.base-path=/actuator
management.endpoint.prometheus.enabled=true
management.endpoint.metrics.enabled=true
management.endpoint.health.enabled=true
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true