server:
  port: 8222

spring:
  application:
    name: gateway

  config:
    enabled: false

  # ? ADD THIS: CORS Configuration
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://intelligent-rh:32000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders:
              - "*"
            allowCredentials: true
            maxAge: 3600

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    org.springframework.cloud.gateway: TRACE



# --- Configuration Actuator & Prometheus ---
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - prometheus
          - metrics
      base-path: /actuator
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
    metrics:
      enabled: true
  # Pas besoin de management.metrics.export.prometheus.enabled
  # Prometheus s'active automatiquement avec la dépendance micrometer-registry-prometheus