welcome:
  message: "Helloooo from recrutement"

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true

