welcome:
  message: "Helloooo from talent"

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka
    registerWithEureka: false
    fetchRegistry: false
  instance:
    preferIpAddress: false

